CI: revert to custom travis config; work around conda build stuff

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,5 +1,12 @@
 version: ~> 1.0
 
+language: python
+os: linux
+dist: xenial
+
+stages:
+  - build
+
 env:
   global:
     # doctr generated secure variable for documentation upload
@@ -22,34 +29,43 @@ env:
     - CONDA_REQUIREMENTS="dev-requirements.txt"
 
 
-
-# Uncomment this block if you would like to make PIP test an allowed failure
-#jobs:
-#  allow_failures:
-#    # This makes the PIP based Python 3.6 optional for passing.
-#    # Remove this block if passing tests with PIP is mandatory for your
-#    # package
-#    - name: "Python 3.6 - PIP"
-
-language: python
-os: linux
-dist: xenial
-
-stages:
-  - build
-  - test
-  - name: deploy
-    if: (branch = master OR tag IS present) AND type != pull_request
-
-import:
-  # Build Stage
-  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-build.yml
-  # Tests Stage
-  # - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-pip.yml
-  # - pcdshub/pcds-ci-helpers:travis/shared_configs/python-tester-conda.yml
-  - pcdshub/pcds-ci-helpers:travis/shared_configs/python-linter.yml
-  - pcdshub/pcds-ci-helpers:travis/shared_configs/docs-build.yml
-  # Deploy Stage
-  - pcdshub/pcds-ci-helpers:travis/shared_configs/pypi-upload.yml
-  - pcdshub/pcds-ci-helpers:travis/shared_configs/doctr-upload.yml
-  - pcdshub/pcds-ci-helpers:travis/shared_configs/anaconda-upload.yml
+jobs:
+  include:
+    - stage: build
+      name: "Python 3.9 - PIP"
+      python: 3.9
+      install:
+        - pip install --upgrade pip
+        - echo "Req File':' ${REQUIREMENTS:=requirements.txt}"
+        - echo "Dev Req File':' ${DEV_REQUIREMENTS:=dev-requirements.txt}"
+        - |
+          # Install requirements
+          if [[ ! -f "${REQUIREMENTS}" ]]; then
+              echo "File not found: ${REQUIREMENTS}" 1>&2
+              travis_terminate 1
+          else
+              pip install --requirement "${REQUIREMENTS}"
+          fi
+        - |
+          # Install development requirements
+          if [[ ! -f "${DEV_REQUIREMENTS}" ]]; then
+              echo "File not found: ${DEV_REQUIREMENTS}" 1>&2
+              travis_terminate 1
+          else
+              pip install --requirement "${DEV_REQUIREMENTS}"
+          fi
+        - |
+          # Install Extras such as PyQt5
+          if [[ ! -z "${PIP_EXTRAS}" ]]; then
+              echo "Installing extra pip dependencies."
+              pip install ${PIP_EXTRAS}
+          fi
+      script:
+        - |
+          set -e
+          if command -v coverage; then
+              coverage run --concurrency=thread --parallel-mode -m pytest -vv
+              (coverage combine && coverage report | grep -v -e ' 0%') || true
+          else
+              python -m pytest -vv
+          fi
